version: '3.8'

services:
  # --- SERVICIO DE BASE DE DATOS (PostgreSQL) ---
  postgres:
    container_name: tfg_db
    image: postgres:16-alpine  # Versión ligera y estable
    environment:
      POSTGRES_USER: admin           # Usuario maestro
      POSTGRES_PASSWORD: password123 # Contraseña maestra
      POSTGRES_DB: schooledule       # <--- AQUÍ SE CREA LA BD "schooledule"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tfg_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d schooledule"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- SERVICIO DE GESTIÓN VISUAL (pgAdmin) ---
  pgadmin:
    container_name: tfg_pgadmin
    image: dpage/pgadmin4
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: rafael.medina.ayuso@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # Entras por http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - tfg_net
    restart: unless-stopped

networks:
  tfg_net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: