spring.application.name=Schooledule

# CONEXIÓN (Asegúrate que coincide con lo que acabamos de poner en el Paso 1)
spring.datasource.url=jdbc:postgresql://localhost:5432/schooledule
spring.datasource.username=postgres
spring.datasource.password=root123

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURACIÓN CRÍTICA PARA ARREGLAR EL ERROR ---
spring.session.store-type=jdbc
# Pon esto en NEVER. Le dice a Spring: "No intentes crear tablas de sesión al iniciar, ya lo haré yo".
spring.session.jdbc.initialize-schema=never